# Generated by Django 5.0.3 on 2024-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_24_7',
            field=models.BooleanField(default=False, verbose_name='Круглосуточно'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Срок годности'),
        ),
    ]
